CROSS_COMPLINER=arm-none-eabi-
CC=$(CROSS_COMPLINER)gcc
LD=$(CROSS_COMPLINER)ld

CFLAG= -g -c -O0
OBJS=uart.o main.o 

all:$(OBJS)
	$(LD) $(OBJS) -Ttext 0x40008000 -o uart.elf
	arm-none-eabi-objcopy -O -S binary uart.elf uart.bin 

%.o:%.c
	$(CC) $(CFLAG) $< -o $@

%.o:%.s
	$(CC) $(CFLAG) $< -o $@

clean:
	rm -rf *.o *.elf